// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.0--rc3
// source: test.proto

package pb_4

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Testfuwu_Tceshi_FullMethodName = "/t4_proto.Testfuwu/Tceshi"
)

// TestfuwuClient is the client API for Testfuwu service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TestfuwuClient interface {
	Tceshi(ctx context.Context, in *TestRqt, opts ...grpc.CallOption) (*TestRsp, error)
}

type testfuwuClient struct {
	cc grpc.ClientConnInterface
}

func NewTestfuwuClient(cc grpc.ClientConnInterface) TestfuwuClient {
	return &testfuwuClient{cc}
}

func (c *testfuwuClient) Tceshi(ctx context.Context, in *TestRqt, opts ...grpc.CallOption) (*TestRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TestRsp)
	err := c.cc.Invoke(ctx, Testfuwu_Tceshi_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TestfuwuServer is the server API for Testfuwu service.
// All implementations must embed UnimplementedTestfuwuServer
// for forward compatibility.
type TestfuwuServer interface {
	Tceshi(context.Context, *TestRqt) (*TestRsp, error)
	mustEmbedUnimplementedTestfuwuServer()
}

// UnimplementedTestfuwuServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTestfuwuServer struct{}

func (UnimplementedTestfuwuServer) Tceshi(context.Context, *TestRqt) (*TestRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Tceshi not implemented")
}
func (UnimplementedTestfuwuServer) mustEmbedUnimplementedTestfuwuServer() {}
func (UnimplementedTestfuwuServer) testEmbeddedByValue()                  {}

// UnsafeTestfuwuServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TestfuwuServer will
// result in compilation errors.
type UnsafeTestfuwuServer interface {
	mustEmbedUnimplementedTestfuwuServer()
}

func RegisterTestfuwuServer(s grpc.ServiceRegistrar, srv TestfuwuServer) {
	// If the following call pancis, it indicates UnimplementedTestfuwuServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Testfuwu_ServiceDesc, srv)
}

func _Testfuwu_Tceshi_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestRqt)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestfuwuServer).Tceshi(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Testfuwu_Tceshi_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestfuwuServer).Tceshi(ctx, req.(*TestRqt))
	}
	return interceptor(ctx, in, info, handler)
}

// Testfuwu_ServiceDesc is the grpc.ServiceDesc for Testfuwu service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Testfuwu_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "t4_proto.Testfuwu",
	HandlerType: (*TestfuwuServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Tceshi",
			Handler:    _Testfuwu_Tceshi_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "test.proto",
}
